### ISSUE TITLE
Fail to run plugin after `plz init plugin go-proto`

### ISSUE THREAD

**Issue by sfirmery** [please-build/go-proto-rules#8]
With plz `17.3.0`, after running `plz init plugin go-proto`, I got the error:

```bash
    ///go_proto//build_defs:go_proto
Parsed build file plz-out/subrepos/plugins/go_proto/build_defs/BUILD but it doesn't contain target go_proto (depended on by //:all)
```

Version of the plugin is `v0.2.0`.
Forcing version `23b5f5c11c7ee4a00e56f871e3abe3e568bfc8ef` makes it works. It seems that this is fixed by #6.

Is it possible to release a new version of this plugin?

**Comment by Tatskaari** [comment]
Yup sure thing! Sorry about that.
